version: "3.8"

services:
  minio:
    image: minio/minio:latest
    container_name: lai_minio
    restart: unless-stopped

    ports:
      - "9000:9000"
      - "9001:9001"

    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}

    volumes:
      - ./data:/data

    command: server /data --console-address ":9001"

    networks:
      - ${MINIO_NETWORK}

networks:
  lai_network:
    external: true
